14 orderservice modells
MateWagner/warehouse-microservices pull request #16
Opened 2023-12-06 14:01 UTC by MateWagner

2023-12-06 16:27 UTC, tuszmak requested changes

2023-12-06 16:27 UTC, tuszmak commented on order-payment/src/main/java/com/codecool/order_payment/data/OrderStatus.java
> +    DELIVER
Ha múlt időben vagyunk, akkor ennek "DELIVERED"-nek kell lennie. Jelenlegi jelen időben van.

2023-12-06 17:32 UTC, MateWagner commented on order-payment/src/main/java/com/codecool/order_payment/modell/Order.java
> +    private BigDecimal total;
https://stackoverflow.com/questions/179427/how-to-resolve-a-java-rounding-double-issue

2023-12-06 17:36 UTC, tuszmak commented on order-payment/src/main/java/com/codecool/order_payment/modell/Order.java
> +    private BigDecimal total;
Értem, akkor nincs egyéb kérdésem

2023-12-07 08:34 UTC, tuszmak approved these changes
LGTM

2023-12-07 08:37 UTC, merged