17 post checkoutapiv1address
MateWagner/warehouse-microservices pull request #19
Opened 2023-12-11 09:51 UTC by MateWagner

We need to consider how we want to deal with the user IDs  because we can send everything from the front end wich

2023-12-11 13:38 UTC, tuszmak requested changes

2023-12-11 13:38 UTC, tuszmak commented on order-payment/src/main/java/com/codecool/order_payment/service/PostcodeService.java
> +}
A hibakezelés szerintem egy kicsit felesleges.

Szerintem ez cleanebb:

```java
 protected Postcode createAndOrGetPostcode(int postcode) {
        if (getByPostcode(postcode).isPresent()) {
            return getByPostcode(postcode).get();
        }
        Postcode postcodeBuilt = Postcode.builder().postcode(postcode).build();
        return postcodeRepository.save(postcodeBuilt);

    }


    private Optional<Postcode> getByPostcode(int postcode) {
        return postcodeRepository.findByPostcode(postcode);
    }
```

2023-12-11 13:38 UTC, tuszmak commented on order-payment/src/main/java/com/codecool/order_payment/service/AddressService.java
> +                ))
A createAndOrGet fgv-eknél az adatkezelés egy picit fura nekem. A PostCodeService-ben leírtam, ahogy látom az összes ugyanúgy épül fel.

2023-12-11 13:43 UTC, tuszmak commented
Regarding the security issue of userIDs. Is it really that easy to forge a UUID?

2023-12-13 07:53 UTC, MateWagner commented on order-payment/src/main/java/com/codecool/order_payment/service/AddressService.java
> +    }
I rather keep unchecked and ControllerAdviser will catches the exception

2023-12-13 08:38 UTC, tuszmak approved these changes
LGTM

2023-12-14 07:37 UTC, merged